name: Deployment (develop)

on:
  push:
    branches:
      - develop

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules-yarn-lock
        with:
          path: node_modules
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-v2-${{ env.cache-name }}-
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

  deploy:
    needs: install
    name: Deploy app to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules-yarn-lock
        with:
          path: node_modules
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-v2-${{ env.cache-name }}-
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        env:
          CORONA_ROOT_URL: /develop/
        with:
          cmd: build
      - name: Deploy
        env:
          GITHUB_PAT: ${{ secrets.GH_CORONA_PAT }}
        run: |
          echo "* Cloning repo"
          git clone https://$GITHUB_PAT@github.com/$GITHUB_REPOSITORY develop-clone
          cd develop-clone

          echo "* Checking out gh-pages"
          git checkout gh-pages

          ls -alF

          echo "* Cleaning existing develop dir"
          [ -d develop ] && rm -R develop

          echo "* Populating develop dir"
          cp -Rv ../dist develop

          echo "* Adding to index"
          git add develop

          echo "* Commit"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Deploy develop branch to GitHub pages"

          echo "* Push"
          git push
